package com.oxymedical.component.appadmin.model.resources_app;
// Generated Nov 16, 2009 2:50:33 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Toolcateogry generated by hbm2java
 */
public class Toolcateogry  implements java.io.Serializable {


     private Integer id;
     private String category;
     private Set<Nodedetail> nodedetails = new HashSet<Nodedetail>(0);

    public Toolcateogry() {
    }

   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public Set<Nodedetail> getNodedetails() {
        return this.nodedetails;
    }
    
    public void setNodedetails(Set<Nodedetail> nodedetails) {
        this.nodedetails = nodedetails;
    }




}


