/* Generated By:JJTree: Do not edit this line. .\RuleParserTreeConstants.java */

package com.oxymedical.component.rulesComponent.parser.javacc;

public interface RuleParserTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTRULESETLINE = 1;
  public int JJTVOID = 2;
  public int JJTVARIABLE = 3;
  public int JJTTYPE = 4;
  public int JJTID = 5;
  public int JJTRULELINE = 6;
  public int JJTSALIENCELINE = 7;
  public int JJTIFLINE = 8;
  public int JJTCONDITION = 9;
  public int JJTTHENLINE = 10;
  public int JJTCONSEQUENCE = 11;
  public int JJTURLLINE = 12;


  public String[] jjtNodeName = {
    "parse",
    "ruleSetLine",
    "void",
    "variable",
    "type",
    "id",
    "ruleLine",
    "salienceLine",
    "ifLine",
    "condition",
    "thenLine",
    "consequence",
    "urlLine",
  };
}
